In [212]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 35)
pd.set_option('display.max_rows', 50)

In [68]:
full_df = pd.read_csv('~/code/janduplessis883/data-showup/data/output-data/training_data_no_features.csv')

### Consider to encode English:1 - Not english: 0

In [29]:
full_df['Language'].value_counts(normalize=True).head(10)

(XaG5t) Main spoken language English       0.738110
(XaG5p) Main spoken language Arabic        0.053154
(XaJD5) Main spoken language Italian       0.022395
(XaG66) Main spoken language Spanish       0.019189
(XaIpr) Main spoken language Farsi         0.018026
(XaG5u) Main spoken language French        0.016384
(XaG62) Main spoken language Portuguese    0.011578
(Ua0HJ) Main spoken language               0.010422
(XaJPA) Main spoken language Tagalog       0.009742
(XaG64) Main spoken language Russian       0.008861
Name: Language, dtype: float64

In [30]:
full_df['Booked by'].value_counts().head(10)

FRANKSON, Joyce (Ms)                   29407
Ms Olive Tuganemaria                   27664
Unknown                                26269
BISHOP, Jane (Reception Supervisor)    25273
DEVLIN, Sharon (Miss)                  24133
HIPPOLYTE, Christine (Ms)              22638
CRUZ MARIA, E                          20040
MARK, Joy                              19525
DE' SOUZA, Lorraine (Reception)        16305
FITZPATRICK, Helen (Mrs)               14557
Name: Booked by, dtype: int64

In [32]:
full_df['Clinician'].value_counts().head(10)

Dr Justin Hammond         43618
ADIB, Burhan (Dr.)        30013
EMILIANI, Orietta (Dr)    27086
Dr Biennita Sapuay        26358
Dr Vikas Mehta            24164
Dr Katherine S Brunton    22616
Elizabeth O'Connor        19135
REES, Timothy (Dr)        17627
Mrs Myra Cosio            17282
Dr William Squier         17250
Name: Clinician, dtype: int64

In [42]:
full_df['Rota type'].value_counts().head(40)

KMC GP                              150148
Redcliffe GP                        112407
Session                              94593
The Good Practice GP                 90789
Stanhope Mews GP                     88329
The Chelsea Practice GP              56742
Earls Court Surgery GP               39546
Stanhope Mews Nurse                  27766
KMC Nurse                            26611
GP Session                           20369
Redcliffe Nurse                      19683
Redcliffe Pharmacist                 17962
KMC Pharmacist                       17253
Redcliffe Registrar                  13564
Health Partners at VM GP             13526
Earls Court Surgery Pharmacist       12585
Redcliffe HCA                        12564
Stanhope Mews Nurse Practitioner     11204
The Chelsea Practice Nurse           10765
HCA Session                           9732
KMC Registrar                         9490
The Chelsea Practice HCA              9324
The Good Practice Nurse               9023
The Good Practice HCA                 8768
Earls Court Surgery HCA               8709
The Chelsea Practice Pharmacist       8231
Redcliffe Extended Hours GP           7652
Nurse Clinic                          7515
The Good Practice Pharmacist          7315
GP Clinic                             7101
Violet Melchett GP                    7078
Earls Court Surgery Nurse             6753
The Good Practice Registrar           6305
Urgent Clinics                        5178
Stanhope Mews Registrar               4412
Telephone Triage                      4299
Stanhope Mews Extended Hours GP       3976
HCA session                           3495
Knightsbridge Extended Hours GP       3462
Locum GP Session                      3214
Name: Rota type, dtype: int64

# Appointment status encoding

In [45]:
full_df['Appointment status'].value_counts()

Finished              981586
Did Not Attend         40300
Arrived                 2825
In Progress             1403
Patient Walked Out       544
Waiting                   99
Name: Appointment status, dtype: int64

In [59]:
full_df

,Appointment booked date,Appointment date,Appointment status,Appointment time,Booked by,Clinician,Rota type,Patient ID,app datetime,temp,precipitation,Age in years,Postcode,Sex,Registration date,Ethnicity category,Language,Registration status,FRAILTY,DEPRESSION,OBESITY,IHD,DM,HPT,NDHG,SMI,Latitude,Longitude,IMD2023,dist_to_station,distance_from_surg
0,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other Mixed,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
1,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
2,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
3,12-May-22,05-Jul-22,Finished,09:00 - 09:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,19580589,2022-07-05 09:00:00,17.7,0.0,40,W8 6JQ,Female,2014-01-07 00:00:00,Other White,(XaG62) Main spoken language Portuguese,Current,0.00,0,0,0,0,0,0,0,51.496001,-0.193468,22698.0,0.519419,0.816996
4,17-May-22,05-Jul-22,Finished,10:00 - 10:59,"LE TELLIER, Jean-Pierre","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,47551135,2022-07-05 10:00:00,18.5,0.0,70,SW3 3SQ,Male,2017-03-06 00:00:00,Indian or British Indian,(XaG5t) Main spoken language English,Current,0.39,0,1,0,1,1,0,0,51.490771,-0.168178,10169.0,0.540792,1.656309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026752,31-Dec-19,31-Dec-19,Finished,15:00 - 15:59,"AMADI, Kasi (Miss)","PATEL, Rinku (Pharmacist)",Redcliffe Pharmacist,47464358,2019-12-31 15:00:00,8.9,0.0,87,SW10 9NG,Male,2003-09-09 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.484323,-0.180246,20040.0,1.056940,0.579572
1026753,31-Dec-19,31-Dec-19,Finished,15:00 - 15:59,"AMADI, Kasi (Miss)","PATEL, Rinku (Pharmacist)",Redcliffe Pharmacist,47493202,2019-12-31 15:00:00,8.9,0.0,36,SW5 0DY,Male,2012-05-02 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,Current,0.06,0,0,0,1,0,0,0,51.489257,-0.189864,14414.0,0.386273,1.348580
1026754,31-Dec-19,31-Dec-19,Finished,15:00 - 15:59,"AMADI, Kasi (Miss)","PATEL, Rinku (Pharmacist)",Redcliffe Pharmacist,47487575,2019-12-31 15:00:00,8.9,0.0,42,SW10 9AL,Female,2011-02-10 00:00:00,Chinese,(XaG5t) Main spoken language English,Current,0.08,0,0,0,0,0,0,0,51.488467,-0.191806,14414.0,0.287596,1.445016
1026755,31-Dec-19,31-Dec-19,Finished,15:00 - 15:59,"DUFFIELD, Katie (Miss)","PATEL, Rinku (Pharmacist)",Redcliffe Pharmacist,47489391,2019-12-31 15:00:00,8.9,0.0,51,SW5 9BY,Female,1976-11-26 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,Current,0.06,1,1,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,1.629449
1026756,31-Dec-19,31-Dec-19,Finished,15:00 - 15:59,"DUFFIELD, Katie (Miss)","PATEL, Rinku (Pharmacist)",Redcliffe Pharmacist,22733122,2019-12-31 15:00:00,8.9,0.0,67,SW5 9PD,Female,2017-02-13 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,Current,0.08,0,0,1,0,1,0,0,51.491521,-0.196266,12666.0,0.136299,1.855587

In [135]:
full_df = pd.read_csv('~/code/janduplessis883/data-showup/data/output-data/training_data_no_features.csv')

In [109]:
full_df['Appointment status'].value_counts()

Finished              981586
Did Not Attend         40300
Arrived                 2825
In Progress             1403
Patient Walked Out       544
Waiting                   99
Name: Appointment status, dtype: int64

In [110]:
full_df.shape

(1026757, 31)

In [111]:
%%time
def encode_appointment_status(df):
    df['App_status_encoded'] = [0 if app_status == 'Did Not Attend' else 1 
                                     for app_status in df['Appointment status']]
    df = df.drop(columns='Appointment status')
    return df
full_df = encode_appointment_status(full_df)

CPU times: user 422 ms, sys: 31.4 ms, total: 453 ms
Wall time: 452 ms

In [112]:
full_df['App_status_encoded'].value_counts()

1    986457
0     40300
Name: App_status_encoded, dtype: int64

In [113]:
full_df.head(1)

,Appointment booked date,Appointment date,Appointment time,Booked by,Clinician,Rota type,Patient ID,app datetime,temp,precipitation,Age in years,Postcode,Sex,Registration date,Ethnicity category,Language,Registration status,FRAILTY,DEPRESSION,OBESITY,IHD,DM,HPT,NDHG,SMI,Latitude,Longitude,IMD2023,dist_to_station,distance_from_surg,App_status_encoded
0,10-May-22,14-Jul-22,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other Mixed,(XaG5t) Main spoken language English,"Deceased, Deducted",0.0,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,1

# Transform the 'Appointment time' column to only capture the hour.

In [115]:
full_df['Appointment time'].isna().sum()

0

### Drop 1 appointment at 2am?

In [119]:
full_df['Appointment time'].value_counts()

09:00 - 09:59    167429
10:00 - 10:59    160340
11:00 - 11:59    141863
15:00 - 15:59    116261
16:00 - 16:59    104941
14:00 - 14:59     83906
12:00 - 12:59     72834
17:00 - 17:59     62193
18:00 - 18:59     35270
13:00 - 13:59     31991
08:00 - 08:59     27737
19:00 - 19:59     12651
20:00 - 20:59      4603
07:00 - 07:59      4575
06:00 - 06:59       120
21:00 - 21:59        42
02:00 - 02:59         1
Name: Appointment time, dtype: int64

In [121]:
full_df['Appointment time'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1026757 entries, 0 to 1026756
Series name: Appointment time
Non-Null Count    Dtype
--------------    -----
1026757 non-null  object
dtypes: object(1)
memory usage: 7.8+ MB

In [136]:
full_df.head()

,Appointment booked date,Appointment date,Appointment status,Appointment time,Booked by,Clinician,Rota type,Patient ID,app datetime,temp,precipitation,Age in years,Postcode,Sex,Registration date,Ethnicity category,Language,Registration status,FRAILTY,DEPRESSION,OBESITY,IHD,DM,HPT,NDHG,SMI,Latitude,Longitude,IMD2023,dist_to_station,distance_from_surg
0,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other Mixed,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
1,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
2,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712
3,12-May-22,05-Jul-22,Finished,09:00 - 09:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,19580589,2022-07-05 09:00:00,17.7,0.0,40,W8 6JQ,Female,2014-01-07 00:00:00,Other White,(XaG62) Main spoken language Portuguese,Current,0.00,0,0,0,0,0,0,0,51.496001,-0.193468,22698.0,0.519419,0.816996
4,17-May-22,05-Jul-22,Finished,10:00 - 10:59,"LE TELLIER, Jean-Pierre","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,47551135,2022-07-05 10:00:00,18.5,0.0,70,SW3 3SQ,Male,2017-03-06 00:00:00,Indian or British Indian,(XaG5t) Main spoken language English,Current,0.39,0,1,0,1,1,0,0,51.490771,-0.168178,10169.0,0.540792,1.656309

## encode_hour_appointment function

In [294]:
full_df = pd.read_csv('~/code/janduplessis883/data-showup/data/output-data/training_data_no_features.csv')
def encode_hour_appointment(df):
    df['Hour_of_appointment'] = df['Appointment time'].str[:2].astype(int)
    df.drop(columns=['Appointment time'], inplace=True)
    return df

full_df = encode_hour_appointment(full_df)

full_df.head()

,Appointment booked date,Appointment date,Appointment status,Booked by,Clinician,Rota type,Patient ID,app datetime,temp,precipitation,Age in years,Postcode,Sex,Registration date,Ethnicity category,Language,Registration status,FRAILTY,DEPRESSION,OBESITY,IHD,DM,HPT,NDHG,SMI,Latitude,Longitude,IMD2023,dist_to_station,distance_from_surg,Hour_of_appointment
0,10-May-22,14-Jul-22,Finished,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other Mixed,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,10
1,10-May-22,14-Jul-22,Finished,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,Other,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,10
2,10-May-22,14-Jul-22,Finished,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,British or Mixed British,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,10
3,12-May-22,05-Jul-22,Finished,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,19580589,2022-07-05 09:00:00,17.7,0.0,40,W8 6JQ,Female,2014-01-07 00:00:00,Other White,(XaG62) Main spoken language Portuguese,Current,0.00,0,0,0,0,0,0,0,51.496001,-0.193468,22698.0,0.519419,0.816996,9
4,17-May-22,05-Jul-22,Finished,"LE TELLIER, Jean-Pierre","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,47551135,2022-07-05 10:00:00,18.5,0.0,70,SW3 3SQ,Male,2017-03-06 00:00:00,Indian or British Indian,(XaG5t) Main spoken language English,Current,0.39,0,1,0,1,1,0,0,51.490771,-0.168178,10169.0,0.540792,1.656309,10

# Ethnic Group Mapping
https://www.ethnicity-facts-figures.service.gov.uk/uk-population-by-ethnicity/national-and-regional-populations/population-of-england-and-wales/1.4

Black:
- African
- Other Black 
- Caribbean

White:
- British or Mixed British
- Other White
- Irish

Mixed:
- White & Black African
- White & Black Caribbean
- White & Asian
- Other Mixed

Asian:
- Other Asian
- Indian or British Indian
- Pakistani or British Pakistani
- Chinese
- Bangladeshi or British Bangladeshi 

Unknown
- Other

In [287]:
full_df = pd.read_csv('~/code/janduplessis883/data-showup/data/output-data/training_data_no_features.csv')

In [288]:
def group_ethnicity_categories(df):
    ethnicity_dict = {'African': 'Black',
                      'Other Black': 'Black',
                      'Caribbean': 'Black',
                      'British or Mixed British': 'White',
                      'Other White': 'White',
                      'Irish': 'White',
                      'White & Black African': 'Mixed',
                      'White & Black Caribbean': 'Mixed',
                      'White & Asian': 'Mixed',
                      'Other Mixed': 'Mixed',
                      'Other Asian': 'Asian',
                      'Indian or British Indian': 'Asian',
                      'Pakistani or British Pakistani': 'Asian',
                      'Chinese': 'Asian',
                      'Bangladeshi or British Bangladeshi': 'Asian',
                      'Other': 'Unknown'}
    df['Ethnicity category'] = df['Ethnicity category'].map(ethnicity_dict)
    return df
full_df = group_ethnicity_categories(full_df)

In [289]:
from sklearn.preprocessing import OneHotEncoder

In [290]:
def ohe_ethnicity(df):
    df = df.rename(columns={'Ethnicity category': 'Ethnicity'})
    ohe = OneHotEncoder(sparse_output=False)
    ohe.fit(df[['Ethnicity']])
    df[ohe.get_feature_names_out()] = ohe.transform(df[['Ethnicity']])
    df.drop(columns=['Ethnicity'], inplace=True)
    return df
full_df = ohe_ethnicity(full_df)

In [292]:
full_df.head()

,Appointment booked date,Appointment date,Appointment status,Appointment time,Booked by,Clinician,Rota type,Patient ID,app datetime,temp,precipitation,Age in years,Postcode,Sex,Registration date,Language,Registration status,FRAILTY,DEPRESSION,OBESITY,IHD,DM,HPT,NDHG,SMI,Latitude,Longitude,IMD2023,dist_to_station,distance_from_surg,Ethnicity_Asian,Ethnicity_Black,Ethnicity_Mixed,Ethnicity_Unknown,Ethnicity_White
0,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,0.0,0.0,1.0,0.0,0.0
1,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,0.0,0.0,0.0,1.0,0.0
2,10-May-22,14-Jul-22,Finished,10:00 - 10:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Registrar,19581842,2022-07-14 10:00:00,21.6,0.0,73,SW5 9BY,Male,2009-08-17 00:00:00,(XaG5t) Main spoken language English,"Deceased, Deducted",0.00,0,0,0,0,0,0,0,51.490204,-0.193625,16808.0,0.136631,0.204712,0.0,0.0,0.0,0.0,1.0
3,12-May-22,05-Jul-22,Finished,09:00 - 09:59,"FLORKO, Aleksandra (Miss)","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,19580589,2022-07-05 09:00:00,17.7,0.0,40,W8 6JQ,Female,2014-01-07 00:00:00,(XaG62) Main spoken language Portuguese,Current,0.00,0,0,0,0,0,0,0,51.496001,-0.193468,22698.0,0.519419,0.816996,0.0,0.0,0.0,0.0,1.0
4,17-May-22,05-Jul-22,Finished,10:00 - 10:59,"LE TELLIER, Jean-Pierre","FLORKO, Aleksandra (Miss)",Earls Court Surgery Nurse,47551135,2022-07-05 10:00:00,18.5,0.0,70,SW3 3SQ,Male,2017-03-06 00:00:00,(XaG5t) Main spoken language English,Current,0.39,0,1,0,1,1,0,0,51.490771,-0.168178,10169.0,0.540792,1.656309,1.0,0.0,0.0,0.0,0.0